### PR TITLE
Export StatusError from module

### PR DESCRIPTION
**Pull request by CameronDiver**
Change-type: patch
Signed-off-by: Cameron Diver <cameron@balena.io>

### CODE REVIEW

**Comment by Page-** [comment]
add to whitelist

**Review by Page- — APPROVED** [review]

**Comment by CameronDiver** [comment]
@resin-ci retest

**Comment by CameronDiver** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Pull request merged**
